pastel-api:
  port: 19932

node:
  # `pastel_id` must match to active `PastelID` from masternode.
  # To check it out first get the active outpoint from `masteronde status`, then filter the result of `tickets list id mine` by this outpoint.
  pastel_id: jXXk5k99wK1ca5ZqC6cXSwiiUv57NNiEAApUBtQCNYPbgXDTVwo1k4vVb8J9CAMtnUC4QrNED4DhUGqKyEZCQS
  server:
    # `listen_address` and `port` must match to `extAddress` from masternode.conf
    listen_addresses: "0.0.0.0"
    port: 4444

p2p:
  listen_addresses: "0.0.0.0"
  port: 4445
  # if not specified, persistent database store is used
  memory_db: true

  # default value is assigned automatically, by concatenated CLI parameter `--work-dir` and `p2p` as a subfolder.
  # data_dir: "path/to/p2p/data/dir"

  # bootstrap_ip: ""
  # bootstrap_port: ""
  # use_stun: true

metadb:
  listen_address: "0.0.0.0"
  http_port: 4001
  raft_port: 4002